# Generated by Django 6.0.2 on 2026-03-12 18:52

import app_video.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=250)),
                ("description", models.TextField(max_length=1000)),
                ("category", models.CharField(max_length=250)),
                (
                    "video_file",
                    models.FileField(upload_to=app_video.models.video_upload_path),
                ),
                (
                    "video_480p",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=app_video.models.video_upload_path,
                    ),
                ),
                (
                    "video_720p",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=app_video.models.video_upload_path,
                    ),
                ),
                (
                    "video_1080p",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=app_video.models.video_upload_path,
                    ),
                ),
                (
                    "video_4k",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=app_video.models.video_upload_path,
                    ),
                ),
                (
                    "thumbnail_url",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=app_video.models.video_upload_path,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
