# Generated by Django 6.0.2 on 2026-03-12 19:21

import app_video.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_video", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="thumbnail_url",
            field=models.ImageField(
                blank=True, null=True, upload_to=app_video.models.thumbnail_upload_path
            ),
        ),
    ]
