# Generated by Django 6.0.2 on 2026-03-12 07:03

import app_video.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_video", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="video_1080p",
            field=models.FileField(
                blank=True, null=True, upload_to=app_video.models.video_upload_path
            ),
        ),
        migrations.AddField(
            model_name="video",
            name="video_480p",
            field=models.FileField(
                blank=True, null=True, upload_to=app_video.models.video_upload_path
            ),
        ),
        migrations.AddField(
            model_name="video",
            name="video_4k",
            field=models.FileField(
                blank=True, null=True, upload_to=app_video.models.video_upload_path
            ),
        ),
        migrations.AddField(
            model_name="video",
            name="video_720p",
            field=models.FileField(
                blank=True, null=True, upload_to=app_video.models.video_upload_path
            ),
        ),
    ]
